name: Tweet Scheduler

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 16 * * *'  # 8 AM PST (16:00 UTC)
    - cron: '0 22 * * *'  # 2 PM PST (22:00 UTC)
    - cron: '0 4 * * *'   # 8 PM PST (04:00 UTC next day)

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  # Personal Access Token for write access
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy==4.14.0
      - name: Run script
        run: python main.py
      - name: Commit index file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add quote_index.json
          git commit -m "Update quote index" || echo "No changes to commit"
          git push
