name: Tweet Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy==4.14.0
      - name: Run script
        run: python main.py
      - name: Commit index file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add quote_index.json
          git commit -m "Update quote index" || echo "No changes to commit"
          git push
